import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "react-hot-toast";
import { ProjectProvider } from "@/context/ProjectContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster
          position="top-right"
          reverseOrder={false}
          toastOptions={{
            duration: 3000,
            style: {
              background: "#1F2937", // Tailwind gray-800
              color: "#F9FAFB", // Tailwind gray-50
              padding: "12px 20px",
              borderRadius: "8px",
            },
          }}
        />
        <div id="modal-root"></div>
        <AuthProvider>
          <ProjectProvider>
            <>
              <Navbar />
              <div className="min-h-1/2">{children}</div>
              <Footer />
            </>
          </ProjectProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
