import Home from "@/ui_pages/Home";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Lume | home",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <Home />
    </div>
  );
};

export default page;
